[Mono.Android] Fix API Level 24 build regarding FileChannel. (#724)
It turned out that there had been a build failure that had been ignored
on the mac jenkins builders:

        obj/Debug/android-24/mcw/Java.Nio.Channels.FileChannel.cs(10,213): error CS0738: 'FileChannel' does not implement interface member 'ISeekableByteChannel.Position(long)'. 'FileChannel.Position(long)' cannot implement 'ISeekableByteChannel.Position(long)' bec
ause it does not have the matching return type of 'ISeekableByteChannel'.
        obj/Debug/android-24/mcw/Java.Nio.Channels.FileChannel.cs(10,213): error CS0738: 'FileChannel' does not implement interface member 'ISeekableByteChannel.Truncate(long)'. 'FileChannel.Truncate(long)' cannot implement 'ISeekableByteChannel.Truncate(long)' bec
ause it does not have the matching return type of 'ISeekableByteChannel'